packaging_format = 2

id = "seaweedfs"
name = "SeaweedFS"
description.en = "SeaweedFS is a versatile and efficient storage system"
description.fr = "SeaweedFS is a versatile and efficient storage system"

version = "4.07~ynh1"

maintainers = [""]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "Apache License 2.0" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://seaweedfs.com/"
#demo = "https://demo.example.com"
#userdoc = "https://yunohost.org/apps"
code = "https://github.com/seaweedfs/seaweedfs"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
# FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
architectures = ['amd64']
multi_instance = false

ldap = false
sso = false

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "200M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

  #  [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
  #  type = "user"
  #  [install.password]
  #  help.en = "Use the help field to add an information for the admin about this question."
  #  help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
  #  type = "password"


    
[resources]
    [resources.sources.main]
    # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
    #    ynh_setup_source --dest_dir="$install_dir"
    # You can also define other assets than "main" and add --source_id="foobar" in the previous command
   url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.07/linux_amd64.tar.gz"
   sha256 = "61c8a132c6753cc6726ab6dcc761e0fb2ae2bf7310b1276e82427f4a33dc2a7b"       
   autoupdate.strategy = "latest_github_tag"
   in_subdir = false
   
   # url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.04/linux_amd64_full.tar.gz"
   # sha256 = "128ca0aa439ce3385e73f3817fa29427cbf0910bf1dac63a4ae0022831d637e7"
   #format = "tar.gz"
   #extract = true
   # autoupdate.strategy = "latest_github_tag"
   
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["datadir"]

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"
    admin.url = "/admin"
    admin.allowed = "admins"
    admin.auth_header = false
    
    [resources.ports]
    admin.default = 23646
    master.default = 9333
    filer.default = 8888
    volume.default = 8080
    api.default = 8333 # port pour s3
    
