packaging_format = 2

id = "seaweedfs"
name = "SeaweedFS"
description.en = "Versatile and efficient storage system"
description.fr = "SystÃ¨me de stockage polyvalent et efficace"

version = "4.12~ynh1"

maintainers = [otm3GHG]

[upstream]
license = "Apache-2.0"
website = "https://seaweedfs.com/"
userdoc = "https://github.com/seaweedfs/seaweedfs/wiki"
code = "https://github.com/seaweedfs/seaweedfs"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ['amd64']
multi_instance = false

ldap = true
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "200M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
   
[resources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.12/linux_amd64.tar.gz"
    amd64.sha256 = "64ec9f243977adda9b82cb288db47552aa2cef06b3a4f3a794eca69751a9ca13"
    arm64.url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.09/linux_arm64.tar.gz"
    arm64.sha256 = "37af21257f2c2b86d6c875d246e37ce5ea33a7bdaa7aaf47e19642e7e4d05157"

    autoupdate.strategy = "latest_github_tag"
   
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["datadir"]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"
    admin.allowed = "admins"
    admin.auth_header = false
    
    [resources.ports]
    admin.default = 23646
    master.default = 9333
    filer.default = 8888
    volume.default = 8080
    api.default = 8333 # port pour s3
